apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: microservices-ticketing-application
build:
  artifacts:
  - image: us.gcr.io/ticketing-dev-345419/auth
    context: services/auth
    docker:
      dockerfile: Dockerfile
  - image: us.gcr.io/ticketing-dev-345419/client
    context: client
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s-prod/ingress-srv.yaml
